server.port: 9191

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oAuthDB?serverTimezone=UTC?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
        

#logs into the console all the querries
logging:
  level:
    org:
      hibernate:
        type: trace 
      